
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <ClerkProvider appearance={{
        layout:{
          logoImageUrl: 'icons/yoom-logo.svg',
          socialButtonsVariant: 'iconButton'
        },
        variables:{
          colorText: '#fff',
          colorPrimary:'#0E78F9',
          colorBackground: '#1c1f2e',
          colorInputBackground:'#252a41',
          colorInputText:'#fff'
        }
      }}>
    <html lang="en">
      <body className={`${inter.className} bg-dark-1`}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
